### ISSUE TITLE
Allow seeing who else uses a certain distro, wm, etc.

### ISSUE THREAD

**Issue by avcado** [unixporn/trup-rs#49]
This has been bugging me that robbb does not have this feature (not to be rude, though. What I mean by "Allow seeing who uses [insert distro/wm/etc.]" is you run (as an example `!top DE/WM berry`, it shows the amount of people using it, the percentage using it, **and the people using it.**

**Comment by elkowar** [comment]
Pretty sure we don't want this:
1. would encourage pinging people directly for the stuff they use (spammy, anoying, and they might not be experts on sth just because they use it, so it'd also just be likely to be useless)
2. for many things would become a very long list
3. WHY?
4. could quickly result in people witchhunting others that use software they dislike (i.e. flame-wars against gnome-users, or whatever)

**Comment by avcado** [comment]
1. fair
2. you can probably have a list where they have to select between page 1 and page 2 of everyone who uses that thing.
3. so that i can see who else uses berrywm
4. isn't bashing software against the rules?

**Comment by elkowar** [comment]
3. Why does it matter?
4. Yes, but it's a very lousily enforced rule, mostly based on the fact that the line between objective discussion and just bashing based on nothing is very very blurry. Also, it being against the rules anyways doesn't make it sensible to actively support it

**Comment by avcado** [comment]
3. i just thought it'd be important
4. fair.
